# Type stubs for the htmlarc extension module (shipped in the wheel by maturin).
# Keep in sync with crates/htmlarc-py/src/lib.rs — the pyclass docstrings there
# are the authoritative behavior reference.

from collections.abc import Iterator
from os import PathLike

__version__: str

class Selector:
    """A compiled CSS selector list — the ``re.compile`` of CSS.

    Compile once and reuse across ``select()`` calls to skip re-parsing the
    selector for every document.
    """

    def __init__(self, css: str) -> None: ...
    @property
    def source(self) -> str: ...

class Document:
    """A parsed HTML document, from ``parse()`` or an ``Archive``."""

    @property
    def key(self) -> str | None: ...
    @property
    def root(self) -> Element: ...
    @property
    def text(self) -> str: ...
    def select(self, selector: str | Selector) -> list[Element]: ...
    def select_first(self, selector: str | Selector) -> Element | None: ...
    def select_text(self, selector: str | Selector) -> list[str]: ...
    def select_attr(self, selector: str | Selector, name: str) -> list[str | None]: ...
    def select_html(self, selector: str | Selector, pretty: bool = False) -> list[str]: ...
    def to_html(self, pretty: bool = False) -> str: ...

class Element:
    """An element within a ``Document`` — a cheap (document, node index) handle."""

    @property
    def document(self) -> Document: ...
    @property
    def index(self) -> int: ...
    @property
    def tag(self) -> str: ...
    @property
    def id(self) -> str | None: ...
    @property
    def classes(self) -> list[str]: ...
    @property
    def attrs(self) -> dict[str, str]: ...
    @property
    def text(self) -> str: ...
    @property
    def own_text(self) -> str | None: ...
    @property
    def css_path(self) -> str: ...
    @property
    def parent(self) -> Element | None: ...
    @property
    def next_sibling(self) -> Element | None: ...
    @property
    def prev_sibling(self) -> Element | None: ...
    @property
    def children(self) -> list[Element]: ...
    def get(self, name: str) -> str | None: ...
    def __getitem__(self, name: str) -> str: ...
    def select(self, selector: str | Selector) -> list[Element]: ...
    def select_first(self, selector: str | Selector) -> Element | None: ...
    def select_text(self, selector: str | Selector) -> list[str]: ...
    def select_attr(self, selector: str | Selector, name: str) -> list[str | None]: ...
    def select_html(self, selector: str | Selector, pretty: bool = False) -> list[str]: ...
    def matches(self, selector: str | Selector) -> bool: ...
    def to_html(self, pretty: bool = False) -> str: ...

class Archive:
    """A read-only, memory-mapped ``.htmlarc`` archive of pre-parsed documents.

    The ``scan_*``/``matching`` sweeps run across all cores with the GIL
    released — prefer them over a Python loop when extracting from every
    document.
    """

    def __init__(self, path: str | PathLike[str]) -> None: ...
    @property
    def path(self) -> str: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, index: int | str) -> Document: ...
    def get(self, key: str) -> Document | None: ...
    def __iter__(self) -> Iterator[Document]: ...
    def matching(self, selector: str | Selector) -> list[str]: ...
    def scan_text(self, selector: str | Selector) -> list[tuple[str, list[str]]]: ...
    def scan_attr(
        self, selector: str | Selector, name: str
    ) -> list[tuple[str, list[str | None]]]: ...

class ArchiveIter:
    def __iter__(self) -> ArchiveIter: ...
    def __next__(self) -> Document: ...

class ArchiveBuilder:
    """Builds a ``.htmlarc`` archive: ``add(key, html)`` then ``write(path)`` once."""

    def __init__(self) -> None: ...
    def add(self, key: str, html: str) -> None: ...
    def write(self, path: str | PathLike[str]) -> None: ...

def parse(html: str) -> Document: ...
def open(path: str | PathLike[str]) -> Archive: ...
