use std::path::PathBuf;

xflags::xflags! {
    src "./src/args.rs"

    /// Convert a ZIM file (the Kiwix/Wikipedia offline format) into an .htmlarc archive.
    cmd zim2htmlarc {
        /// List the HTML articles (title <tab> url) in a ZIM file.
        cmd list {
            /// The .zim file to read.
            required file: PathBuf
        }

        /// Print one article's HTML to stdout, found by exact title.
        cmd extract {
            /// The .zim file to read.
            required file: PathBuf
            /// The exact article title to extract.
            required title: String
        }

        /// Export a ZIM's HTML articles into a single .htmlarc archive.
        cmd export {
            /// The .zim file to read.
            required file: PathBuf
            /// The .htmlarc archive to write.
            required output: PathBuf
            /// Only export articles whose title is in this file (one title per line).
            optional --list wordlist: PathBuf
        }
    }
}
// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Zim2htmlarc {
    pub subcommand: Zim2htmlarcCmd,
}

#[derive(Debug)]
pub enum Zim2htmlarcCmd {
    List(List),
    Extract(Extract),
    Export(Export),
}

#[derive(Debug)]
pub struct List {
    pub file: PathBuf,
}

#[derive(Debug)]
pub struct Extract {
    pub file: PathBuf,
    pub title: String,
}

#[derive(Debug)]
pub struct Export {
    pub file: PathBuf,
    pub output: PathBuf,

    pub list: Option<PathBuf>,
}

impl Zim2htmlarc {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
