[package]
name = "htmlarc-dom"
description = "A flat, byte-array, rkyv-archivable HTML DOM with a parser and CSS3 selector engine"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
function_name.workspace = true
indexmap.workspace = true
log.workspace = true
rkyv = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tinyvec = { workspace = true, features = ["alloc"] }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
insta = { workspace = true, features = ["glob"] }

[[bench]]
harness = false
name = "parsing"

[[bench]]
harness = false
name = "repackaging"

[[bench]]
harness = false
name = "selectors"

[[bench]]
harness = false
name = "iteration"

[[bench]]
harness = false
name = "loading"
