use std::path::PathBuf;

xflags::xflags! {
    src "./src/args.rs"

    /// Pack a corpus of HTML into one archive and CSS-query it without re-parsing.
    ///
    /// Every command takes a <source>, which is one of:
    ///   - a .htmlarc archive file (loaded directly, no parsing),
    ///   - a single .html/.htm file (parsed into a one-entry archive),
    ///   - a directory of *.html files (each parsed, keyed by file name).
    cmd htmlarc {
        /// List the keys (documents) in a source, optionally filtered.
        cmd list {
            /// .htmlarc file, .html file, or directory of *.html.
            required source: PathBuf

            /// Keep only documents matching an expression, one of:
            ///   a) 'css: section > h1'  b) 'words: a, list'  c) 'path/words.tsv'
            repeated -i, --include expr: String
            /// Drop documents matching an expression (same syntax as --include).
            repeated -x, --exclude expr: String
            /// Only retain the first n matching documents.
            optional -c, --first-n count: usize
            /// Emit raw HTML instead of pretty-printed HTML when writing files.
            optional --raw-html
            /// Write each matching document's HTML into this directory (keys go to words.tsv).
            optional --to-folder path: PathBuf
            /// Navigate documents one by one in the terminal (left/right arrows).
            optional -n, --navigate
        }

        /// Count CSS-selector matches across all documents in a source.
        cmd probe {
            /// .htmlarc file, .html file, or directory of *.html.
            required source: PathBuf

            /// Keep only documents matching an expression (see `list --include`).
            repeated -i, --include expr: String
            /// Drop documents matching an expression.
            repeated -x, --exclude expr: String
            /// A probe '<css> => <format><attr-selector><@words>'. Formats: HtmlFmt, CssFmt,
            /// CssTerse. Example: 'section > h1 => HtmlFmt[id][class^=mw]@words'
            repeated -p, --probe expr: String
        }

        /// Diff two sources by per-document checksum (fast). Lists documents present in
        /// `other` whose content differs from `source`.
        cmd diff {
            /// The first source.
            required source: PathBuf
            /// The second source to compare against.
            required other: PathBuf

            /// Emit raw HTML instead of pretty-printed HTML when writing files.
            optional --raw-html
            /// Write differing documents into this directory (<key>.1.html / <key>.2.html).
            optional --to-folder path: PathBuf
            /// Navigate differing documents one by one (diff.1.html / diff.2.html).
            optional -n, --navigate
        }

        /// Parse a source and write it out as a single .htmlarc archive.
        cmd pack {
            /// .html file or directory of *.html to pack (a .htmlarc is just re-saved).
            required source: PathBuf
            /// Output archive path.
            required -o, --output path: PathBuf
        }
    }
}
// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Htmlarc {
    pub subcommand: HtmlarcCmd,
}

#[derive(Debug)]
pub enum HtmlarcCmd {
    List(List),
    Probe(Probe),
    Diff(Diff),
    Pack(Pack),
}

#[derive(Debug)]
pub struct List {
    pub source: PathBuf,

    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub first_n: Option<usize>,
    pub raw_html: bool,
    pub to_folder: Option<PathBuf>,
    pub navigate: bool,
}

#[derive(Debug)]
pub struct Probe {
    pub source: PathBuf,

    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub probe: Vec<String>,
}

#[derive(Debug)]
pub struct Diff {
    pub source: PathBuf,
    pub other: PathBuf,

    pub raw_html: bool,
    pub to_folder: Option<PathBuf>,
    pub navigate: bool,
}

#[derive(Debug)]
pub struct Pack {
    pub source: PathBuf,

    pub output: PathBuf,
}

impl Htmlarc {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
